CREATE TABLE IF NOT EXISTS order1(
ORD_ID int NOT NULL,
ORD_AMOUNT int NOT NULL,
ORD_DATE DATE NOT NULL,
CUS_ID int NOT NULL,
PRICING_ID int NOT NULL,
PRIMARY KEY (ORD_ID),
FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
FOREIGN KEY (PRICING_ID) REFERENCES SUPPLIER_PRICING(PRICING_ID)
);
 